apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustersecretoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clustersecretoperator
  template:
    metadata:
      labels:
        name: clustersecretoperator
    spec:
      containers:
        - name: clustersecretoperator
          image: justinbarrick/clustersecretoperator:master-d77ed61
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
