kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: clustersecretoperator
  namespace: clustersecrets
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
- apiGroups:
  - clustersecret.codesink.net
  resources:
  - "*"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-clustersecretoperator
subjects:
- kind: ServiceAccount
  name: default
  namespace: clustersecrets
roleRef:
  kind: ClusterRole
  name: clustersecretoperator
  apiGroup: rbac.authorization.k8s.io
